"""ReportLab PDF Generation Engine producing boardroom-ready executive business reports."""

import io
import logging
from typing import Any, Dict, List, Optional
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.reporting.constants import (
    ACCENT_COLOR_HEX,
    BG_LIGHT_HEX,
    BORDER_COLOR_HEX,
    DANGER_COLOR_HEX,
    MUTED_COLOR_HEX,
    PRIMARY_COLOR_HEX,
    SECONDARY_COLOR_HEX,
    TEXT_COLOR_HEX,
    WARNING_COLOR_HEX,
)
from app.reporting.report_templates import ReportDocument, ReportSection

logger = logging.getLogger(__name__)


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas calculating total pages to render 'Page X of Y',
    running corporate headers, and confidentiality notices.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        # Skip header/footer on cover page (Page 1)
        if self._pageNumber == 1:
            return

        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor(MUTED_COLOR_HEX))

        # Running Header
        self.drawString(54, 750, "DecisionOS Executive Intelligence")
        self.drawRightString(612 - 54, 750, "Boardroom Confidential")
        self.setStrokeColor(colors.HexColor(BORDER_COLOR_HEX))
        self.setLineWidth(0.5)
        self.line(54, 742, 612 - 54, 742)

        # Running Footer
        self.line(54, 50, 612 - 54, 50)
        self.drawString(54, 38, "Generated by DecisionOS Explainable AI Platform")
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(612 - 54, 38, page_str)
        self.restoreState()


class PDFGenerator:
    """
    Compiles a structured ReportDocument into a professional PDF binary.
    """

    @classmethod
    def generate(cls, document: ReportDocument, output_path: Optional[str] = None) -> bytes:
        """
        Generates PDF document and returns raw bytes (and optionally writes to file).
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer if not output_path else output_path,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=64,
            bottomMargin=64,
        )

        styles = cls._get_styles()
        story = []

        # 1. Cover Page
        story.extend(cls._build_cover_page(document, styles))
        story.append(PageBreak())

        # 2. Document Sections
        for section in document.sections:
            story.extend(cls._build_section_flowables(section, styles))

        # 3. Evidence References Appendix
        if document.evidence_references:
            story.extend(cls._build_evidence_appendix(document.evidence_references, styles))

        # Build PDF
        doc.build(story, canvasmaker=NumberedCanvas)

        if output_path:
            with open(output_path, "rb") as f:
                return f.read()

        buffer.seek(0)
        return buffer.getvalue()

    @classmethod
    def _get_styles(cls) -> Dict[str, ParagraphStyle]:
        """Custom typography hierarchy for executive reporting."""
        base = getSampleStyleSheet()

        return {
            "CoverCompany": ParagraphStyle(
                "CoverCompany",
                parent=base["Normal"],
                fontName="Helvetica-Bold",
                fontSize=14,
                leading=18,
                textColor=colors.HexColor(SECONDARY_COLOR_HEX),
                alignment=TA_LEFT,
                spaceAfter=15,
            ),
            "CoverTitle": ParagraphStyle(
                "CoverTitle",
                parent=base["Title"],
                fontName="Helvetica-Bold",
                fontSize=26,
                leading=32,
                textColor=colors.HexColor(PRIMARY_COLOR_HEX),
                alignment=TA_LEFT,
                spaceAfter=12,
            ),
            "CoverSubtitle": ParagraphStyle(
                "CoverSubtitle",
                parent=base["Normal"],
                fontName="Helvetica",
                fontSize=12,
                leading=16,
                textColor=colors.HexColor(MUTED_COLOR_HEX),
                alignment=TA_LEFT,
                spaceAfter=25,
            ),
            "SectionTitle": ParagraphStyle(
                "SectionTitle",
                parent=base["Heading1"],
                fontName="Helvetica-Bold",
                fontSize=16,
                leading=20,
                textColor=colors.HexColor(PRIMARY_COLOR_HEX),
                spaceBefore=14,
                spaceAfter=8,
            ),
            "BodyText": ParagraphStyle(
                "BodyText",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=10,
                leading=14,
                textColor=colors.HexColor(TEXT_COLOR_HEX),
                alignment=TA_JUSTIFY,
                spaceAfter=10,
            ),
            "CalloutText": ParagraphStyle(
                "CalloutText",
                parent=base["Normal"],
                fontName="Helvetica-Bold",
                fontSize=10,
                leading=14,
                textColor=colors.HexColor(PRIMARY_COLOR_HEX),
            ),
            "TableHeader": ParagraphStyle(
                "TableHeader",
                parent=base["Normal"],
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=11,
                textColor=colors.white,
                alignment=TA_LEFT,
            ),
            "TableCell": ParagraphStyle(
                "TableCell",
                parent=base["Normal"],
                fontName="Helvetica",
                fontSize=8.5,
                leading=11,
                textColor=colors.HexColor(TEXT_COLOR_HEX),
                alignment=TA_LEFT,
            ),
        }

    @classmethod
    def _build_cover_page(cls, document: ReportDocument, styles: Dict[str, ParagraphStyle]) -> List[Any]:
        meta = document.metadata
        flowables = [
            Spacer(1, 40),
            Paragraph(meta.company_name.upper(), styles["CoverCompany"]),
            Paragraph(meta.title, styles["CoverTitle"]),
            HRFlowable(width="100%", thickness=3, color=colors.HexColor(SECONDARY_COLOR_HEX), spaceBefore=5, spaceAfter=15),
            Paragraph(meta.subtitle or "Deterministic Intelligence Telemetry & Analytical Briefing", styles["CoverSubtitle"]),
            Spacer(1, 100),
        ]

        # Health status badge color
        status_color = ACCENT_COLOR_HEX if meta.business_health_score >= 80 else (
            WARNING_COLOR_HEX if meta.business_health_score >= 60 else DANGER_COLOR_HEX
        )

        meta_table_data = [
            [
                Paragraph("<b>Dataset Name:</b>", styles["TableCell"]),
                Paragraph(meta.dataset_name, styles["TableCell"]),
            ],
            [
                Paragraph("<b>Business Health Score:</b>", styles["TableCell"]),
                Paragraph(f"<font color='{status_color}'><b>{meta.business_health_score}/100 ({meta.business_health_status})</b></font>", styles["TableCell"]),
            ],
            [
                Paragraph("<b>Report Date:</b>", styles["TableCell"]),
                Paragraph(meta.generated_at, styles["TableCell"]),
            ],
            [
                Paragraph("<b>Engine Platform:</b>", styles["TableCell"]),
                Paragraph(meta.decisionos_version, styles["TableCell"]),
            ],
        ]

        meta_table = Table(meta_table_data, colWidths=[160, 344])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(BG_LIGHT_HEX)),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(BORDER_COLOR_HEX)),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor(BORDER_COLOR_HEX)),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 12),
            ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ]))

        flowables.append(meta_table)
        return flowables

    @classmethod
    def _build_section_flowables(cls, section: ReportSection, styles: Dict[str, ParagraphStyle]) -> List[Any]:
        flowables = [
            Paragraph(section.title, styles["SectionTitle"]),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor(BORDER_COLOR_HEX), spaceBefore=2, spaceAfter=8),
        ]

        # Callout box if present
        if section.callout:
            callout_p = Paragraph(f"<b>Key Takeaway:</b> {section.callout}", styles["CalloutText"])
            callout_table = Table([[callout_p]], colWidths=[504])
            callout_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor(BG_LIGHT_HEX)),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(SECONDARY_COLOR_HEX)),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ]))
            flowables.append(callout_table)
            flowables.append(Spacer(1, 8))

        # Content narrative
        if section.content:
            flowables.append(Paragraph(section.content, styles["BodyText"]))

        # Structured table rendering
        if section.data:
            table_flowable = cls._render_section_data_table(section.data, styles)
            if table_flowable:
                flowables.append(table_flowable)
                flowables.append(Spacer(1, 10))

        flowables.append(Spacer(1, 12))
        return flowables

    @classmethod
    def _render_section_data_table(cls, data: Dict[str, Any], styles: Dict[str, ParagraphStyle]) -> Optional[Table]:
        """Dynamically renders structured table objects."""
        if "metrics_table" in data and data["metrics_table"]:
            rows = [[
                Paragraph("Metric Name", styles["TableHeader"]),
                Paragraph("Category", styles["TableHeader"]),
                Paragraph("Value", styles["TableHeader"]),
            ]]
            for item in data["metrics_table"][:10]:
                rows.append([
                    Paragraph(item.get("metric_name", ""), styles["TableCell"]),
                    Paragraph(item.get("category", ""), styles["TableCell"]),
                    Paragraph(str(item.get("value", "")), styles["TableCell"]),
                ])
            t = Table(rows, colWidths=[220, 160, 124])
            cls._apply_table_styling(t)
            return t

        if "findings_table" in data and data["findings_table"]:
            rows = [[
                Paragraph("Diagnostic Finding", styles["TableHeader"]),
                Paragraph("Severity", styles["TableHeader"]),
                Paragraph("Business Impact", styles["TableHeader"]),
                Paragraph("Confidence", styles["TableHeader"]),
            ]]
            for item in data["findings_table"][:6]:
                rows.append([
                    Paragraph(item.get("title", ""), styles["TableCell"]),
                    Paragraph(item.get("severity", ""), styles["TableCell"]),
                    Paragraph(item.get("impact", ""), styles["TableCell"]),
                    Paragraph(item.get("confidence", ""), styles["TableCell"]),
                ])
            t = Table(rows, colWidths=[160, 70, 214, 60])
            cls._apply_table_styling(t)
            return t

        if "root_causes_table" in data and data["root_causes_table"]:
            rows = [[
                Paragraph("Root Cause Driver", styles["TableHeader"]),
                Paragraph("Impacted Symptom", styles["TableHeader"]),
                Paragraph("Strength", styles["TableHeader"]),
                Paragraph("Impact Score", styles["TableHeader"]),
            ]]
            for item in data["root_causes_table"][:5]:
                rows.append([
                    Paragraph(item.get("cause", ""), styles["TableCell"]),
                    Paragraph(item.get("effect", ""), styles["TableCell"]),
                    Paragraph(item.get("strength", ""), styles["TableCell"]),
                    Paragraph(item.get("impact_score", ""), styles["TableCell"]),
                ])
            t = Table(rows, colWidths=[170, 174, 80, 80])
            cls._apply_table_styling(t)
            return t

        if "recommendations_table" in data and data["recommendations_table"]:
            rows = [[
                Paragraph("Strategic Action", styles["TableHeader"]),
                Paragraph("Priority", styles["TableHeader"]),
                Paragraph("Expected Impact", styles["TableHeader"]),
                Paragraph("Effort", styles["TableHeader"]),
            ]]
            for item in data["recommendations_table"][:6]:
                rows.append([
                    Paragraph(item.get("title", ""), styles["TableCell"]),
                    Paragraph(item.get("priority", ""), styles["TableCell"]),
                    Paragraph(item.get("impact", ""), styles["TableCell"]),
                    Paragraph(item.get("effort", ""), styles["TableCell"]),
                ])
            t = Table(rows, colWidths=[264, 80, 80, 80])
            cls._apply_table_styling(t)
            return t

        if "forecasts_table" in data and data["forecasts_table"]:
            rows = [[
                Paragraph("Metric Key", styles["TableHeader"]),
                Paragraph("Model Type", styles["TableHeader"]),
                Paragraph("MAPE Error", styles["TableHeader"]),
                Paragraph("Projected Periods", styles["TableHeader"]),
            ]]
            for item in data["forecasts_table"][:5]:
                rows.append([
                    Paragraph(item.get("metric_key", ""), styles["TableCell"]),
                    Paragraph(item.get("model_type", ""), styles["TableCell"]),
                    Paragraph(item.get("mape", ""), styles["TableCell"]),
                    Paragraph(str(item.get("periods", "")), styles["TableCell"]),
                ])
            t = Table(rows, colWidths=[180, 140, 94, 90])
            cls._apply_table_styling(t)
            return t

        if "scenarios_table" in data and data["scenarios_table"]:
            rows = [[
                Paragraph("Scenario Name", styles["TableHeader"]),
                Paragraph("Simulation Status", styles["TableHeader"]),
                Paragraph("Assumptions Count", styles["TableHeader"]),
            ]]
            for item in data["scenarios_table"][:5]:
                rows.append([
                    Paragraph(item.get("name", ""), styles["TableCell"]),
                    Paragraph(item.get("status", ""), styles["TableCell"]),
                    Paragraph(str(item.get("assumptions_count", "")), styles["TableCell"]),
                ])
            t = Table(rows, colWidths=[250, 134, 120])
            cls._apply_table_styling(t)
            return t

        return None

    @classmethod
    def _apply_table_styling(cls, table: Table):
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(PRIMARY_COLOR_HEX)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor(BORDER_COLOR_HEX)),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor(BORDER_COLOR_HEX)),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor(BG_LIGHT_HEX)]),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))

    @classmethod
    def _build_evidence_appendix(cls, evidence: List[Dict[str, Any]], styles: Dict[str, ParagraphStyle]) -> List[Any]:
        flowables = [
            Paragraph("Appendix: Evidence References & Verification Traceability", styles["SectionTitle"]),
            HRFlowable(width="100%", thickness=1, color=colors.HexColor(BORDER_COLOR_HEX), spaceBefore=2, spaceAfter=8),
            Paragraph("All statements and findings in this report trace to deterministic analytical models and verified platform telemetry.", styles["BodyText"]),
        ]
        rows = [[
            Paragraph("Artifact UUID", styles["TableHeader"]),
            Paragraph("Category", styles["TableHeader"]),
            Paragraph("Title / Descriptor", styles["TableHeader"]),
        ]]
        for ev in evidence[:10]:
            rows.append([
                Paragraph(ev.get("id", ""), styles["TableCell"]),
                Paragraph(ev.get("type", ""), styles["TableCell"]),
                Paragraph(ev.get("title") or ev.get("metric_key") or ev.get("name") or "", styles["TableCell"]),
            ])
        t = Table(rows, colWidths=[200, 130, 174])
        cls._apply_table_styling(t)
        flowables.append(t)
        flowables.append(Spacer(1, 10))
        return flowables
