"""Execution package for Phase 12: Strategic Execution Layer."""

from app.execution.constants import (
    EXECUTION_ENGINE_VERSION,
    EXECUTION_HEALTH_SCORE_VERSION,
    EXECUTION_RISK_ENGINE_VERSION,
    EXECUTION_SCHEMA_VERSION,
    EXECUTION_SNAPSHOT_VERSION,
    LINEAGE_GRAPH_VERSION,
    OUTCOME_ENGINE_VERSION,
    PROGRAM_ROLLUP_VERSION,
    DependencyType,
    ExecutionBlocker,
    ExecutionEventType,
    ExecutionHealthGrade,
    ExecutionRiskLevel,
    GovernanceDecision,
    InitiativePriority,
    InitiativeStatus,
    MilestoneStatus,
    OutcomeMeasurementConfidence,
    ProgramStatus,
    ProgramTemplateCode,
    calculate_health_grade,
)
from app.execution.event_dispatcher import ExecutionEventDispatcher
from app.execution.models import (
    ExecutionSnapshot,
    InitiativeDependency,
    InitiativeExecutionEvent,
    InitiativeMilestone,
    InitiativeOutcome,
    InitiativeReview,
    InitiativeTargetMetric,
    StrategicInitiative,
    StrategicProgram,
)
from app.execution.state_machine import InitiativeStateMachine
from app.execution.templates import SYSTEM_PROGRAM_TEMPLATES, get_template, list_templates

__all__ = [
    "EXECUTION_ENGINE_VERSION",
    "EXECUTION_SCHEMA_VERSION",
    "EXECUTION_SNAPSHOT_VERSION",
    "PROGRAM_ROLLUP_VERSION",
    "EXECUTION_HEALTH_SCORE_VERSION",
    "EXECUTION_RISK_ENGINE_VERSION",
    "OUTCOME_ENGINE_VERSION",
    "LINEAGE_GRAPH_VERSION",
    "ProgramTemplateCode",
    "ProgramStatus",
    "InitiativeStatus",
    "InitiativePriority",
    "ExecutionHealthGrade",
    "ExecutionRiskLevel",
    "ExecutionBlocker",
    "DependencyType",
    "MilestoneStatus",
    "ExecutionEventType",
    "GovernanceDecision",
    "OutcomeMeasurementConfidence",
    "calculate_health_grade",
    "InitiativeStateMachine",
    "ExecutionEventDispatcher",
    "SYSTEM_PROGRAM_TEMPLATES",
    "get_template",
    "list_templates",
    "StrategicProgram",
    "StrategicInitiative",
    "InitiativeExecutionEvent",
    "InitiativeDependency",
    "InitiativeTargetMetric",
    "InitiativeMilestone",
    "InitiativeReview",
    "InitiativeOutcome",
    "ExecutionSnapshot",
]
