import React, { useState } from 'react';
import { Sparkles, Send, ShieldCheck, CheckCircle2, Cpu, ArrowRight, CornerDownLeft, AlertTriangle } from 'lucide-react';
import { ExplainabilityDrawer } from '../../components/workspace/ExplainabilityDrawer';

export const AIAnalystWorkspaceView: React.FC = () => {
  const [inputQuery, setInputQuery] = useState('');
  const [isExplainOpen, setIsExplainOpen] = useState(false);
  const [messages, setMessages] = useState([
    {
      role: 'user',
      text: 'Why is customer retention declining in Southeastern corridors?',
    },
    {
      role: 'assistant',
      text: 'Customer Retention declined by -7.3% (79.5% vs 85.8% target) due to Delivery Latency increasing to 5.4 days (+68.8% vs 3.2d baseline) in Southeastern shipping corridors. This was generated by RootCauseEngine tracing courier SLA non-compliance (78.4% vs 92.0% target). Causal resolution is actively addressed via Recommendation "Carrier Rebalancing & Automated SLA Penalties" (INIT-2026-001).',
      confidence: 0.91,
      breakdown: { telemetry: 0.95, graph: 0.92, causal: 0.87, outcome: 0.89 },
      citations: [
        { name: 'Secondary Hub Dispatch Bottleneck (Root Cause #4)', snapshot: 'V1', conf: 0.94 },
        { name: 'Carrier Rebalancing & Automated SLA Penalties (Rec #1)', snapshot: 'V1', conf: 0.92 },
      ],
    },
  ]);

  const handleSend = (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!inputQuery.trim()) return;

    const userText = inputQuery;
    setInputQuery('');

    setMessages((prev) => [
      ...prev,
      { role: 'user', text: userText },
      {
        role: 'assistant',
        text: `Based on verified Graph Snapshot V3 and digital twin simulation runs, "${userText}" is grounded in verified telemetry: Recommendation #1 deployed via INIT-2026-001 delivers +$124,000 verified ARR recovery with a +11.0 points health score lift.`,
        confidence: 0.92,
        breakdown: { telemetry: 0.95, graph: 0.92, causal: 0.89, outcome: 0.92 },
        citations: [
          { name: 'Verified Outcome: +$124K ARR Recovery', snapshot: 'V3', conf: 0.96 },
        ],
      },
    ]);
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', paddingBottom: '40px', height: 'calc(100vh - 120px)' }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px' }}>
        <div>
          <div style={{ fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: '#A855F7', fontWeight: 800 }}>
            Deterministic Zero-Hallucination C-Suite Analyst
          </div>
          <h1 style={{ fontSize: '1.8rem', fontWeight: 900, color: '#FFFFFF', margin: '4px 0 0 0' }}>
            Explainable AI Analyst Workspace
          </h1>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'rgba(168, 85, 247, 0.1)', border: '1px solid rgba(168, 85, 247, 0.25)', padding: '6px 14px', borderRadius: '20px' }}>
          <Sparkles size={14} color="#A855F7" />
          <span style={{ fontSize: '0.78rem', color: '#A855F7', fontWeight: 700 }}>AI Ready: 94.7% • 100% Citation Coverage • Pinned to Snapshot V3</span>
        </div>
      </div>

      {/* Main 2-Column Chat + Confidence & Citation Layout */}
      <div style={{ display: 'grid', gridTemplateColumns: '2fr 1fr', gap: '20px', flex: 1, minHeight: 0 }}>
        {/* Left: Chat Stream */}
        <div style={{ background: '#090D14', border: '1px solid #1E293B', borderRadius: '12px', padding: '20px', display: 'flex', flexDirection: 'column', minHeight: 0 }}>
          {/* Message List */}
          <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '14px', paddingRight: '6px' }}>
            {messages.map((m, idx) => (
              <div
                key={idx}
                style={{
                  alignSelf: m.role === 'user' ? 'flex-end' : 'flex-start',
                  maxWidth: '85%',
                  background: m.role === 'user' ? '#0284C7' : 'rgba(15, 23, 42, 0.9)',
                  border: m.role === 'user' ? 'none' : '1px solid #1E293B',
                  borderRadius: '10px',
                  padding: '14px 18px',
                  color: '#FFFFFF',
                }}
              >
                <div style={{ fontSize: '0.72rem', color: m.role === 'user' ? 'rgba(255,255,255,0.8)' : '#A855F7', fontWeight: 800, textTransform: 'uppercase', marginBottom: '4px' }}>
                  {m.role === 'user' ? 'Executive Inquiry' : 'Grounded AI Analyst'}
                </div>
                <div style={{ fontSize: '0.88rem', lineHeight: 1.6, color: m.role === 'user' ? '#FFFFFF' : '#CBD5E1' }}>
                  {m.text}
                </div>

                {m.citations && (
                  <div style={{ marginTop: '10px', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '8px', display: 'flex', flexDirection: 'column', gap: '4px' }}>
                    <span style={{ fontSize: '0.68rem', color: '#64748B', fontWeight: 700, textTransform: 'uppercase' }}>Deterministic Citations:</span>
                    {m.citations.map((c, cIdx) => (
                      <div
                        key={cIdx}
                        onClick={() => setIsExplainOpen(true)}
                        style={{ fontSize: '0.75rem', color: '#38BDF8', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
                      >
                        <span>• {c.name} ({c.snapshot})</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Chat Input */}
          <form onSubmit={handleSend} style={{ display: 'flex', gap: '10px', marginTop: '16px' }}>
            <input
              type="text"
              placeholder="Ask AI Analyst (e.g. Which initiative produced the highest ARR?)"
              value={inputQuery}
              onChange={(e) => setInputQuery(e.target.value)}
              style={{
                flex: 1,
                padding: '12px 16px',
                background: 'rgba(15, 23, 42, 0.8)',
                border: '1px solid #1E293B',
                borderRadius: '8px',
                color: '#FFFFFF',
                fontSize: '0.85rem',
                outline: 'none',
              }}
            />
            <button
              type="submit"
              style={{
                padding: '0 18px',
                background: '#A855F7',
                border: 'none',
                borderRadius: '8px',
                color: '#FFFFFF',
                cursor: 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <Send size={16} />
            </button>
          </form>
        </div>

        {/* Right: 4-Factor Confidence & Provenance Sidebar */}
        <div style={{ background: '#090D14', border: '1px solid #1E293B', borderRadius: '12px', padding: '20px', display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div style={{ fontSize: '0.9rem', fontWeight: 800, color: '#FFFFFF' }}>4-Factor Confidence Breakdown</div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: '#94A3B8', marginBottom: '4px' }}>
                <span>Telemetry Confidence</span>
                <span style={{ color: '#10B981', fontWeight: 700 }}>95%</span>
              </div>
              <div style={{ width: '100%', height: '6px', background: '#1E293B', borderRadius: '3px', overflow: 'hidden' }}>
                <div style={{ width: '95%', height: '100%', background: '#10B981' }} />
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: '#94A3B8', marginBottom: '4px' }}>
                <span>Graph Topology Confidence</span>
                <span style={{ color: '#38BDF8', fontWeight: 700 }}>92%</span>
              </div>
              <div style={{ width: '100%', height: '6px', background: '#1E293B', borderRadius: '3px', overflow: 'hidden' }}>
                <div style={{ width: '92%', height: '100%', background: '#38BDF8' }} />
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: '#94A3B8', marginBottom: '4px' }}>
                <span>Causal Lineage Confidence</span>
                <span style={{ color: '#A855F7', fontWeight: 700 }}>87%</span>
              </div>
              <div style={{ width: '100%', height: '6px', background: '#1E293B', borderRadius: '3px', overflow: 'hidden' }}>
                <div style={{ width: '87%', height: '100%', background: '#A855F7' }} />
              </div>
            </div>

            <div>
              <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', color: '#94A3B8', marginBottom: '4px' }}>
                <span>Outcome Validation</span>
                <span style={{ color: '#F59E0B', fontWeight: 700 }}>89%</span>
              </div>
              <div style={{ width: '100%', height: '6px', background: '#1E293B', borderRadius: '3px', overflow: 'hidden' }}>
                <div style={{ width: '89%', height: '100%', background: '#F59E0B' }} />
              </div>
            </div>
          </div>

          <div style={{ marginTop: 'auto', borderTop: '1px solid #1E293B', paddingTop: '16px' }}>
            <button
              onClick={() => setIsExplainOpen(true)}
              style={{
                width: '100%',
                padding: '10px',
                background: 'rgba(30, 41, 59, 0.8)',
                border: '1px solid #334155',
                borderRadius: '6px',
                color: '#F1F5F9',
                fontSize: '0.82rem',
                fontWeight: 700,
                cursor: 'pointer',
              }}
            >
              Open 5-Step Provenance Drawer
            </button>
          </div>
        </div>
      </div>

      {/* Explainability Drawer */}
      <ExplainabilityDrawer
        isOpen={isExplainOpen}
        onClose={() => setIsExplainOpen(false)}
        title="AI Response Causal Lineage"
        metricValue="91.0% Composite Confidence (Verified)"
      />
    </div>
  );
};
