"""ChatPromptBuilder formulating standardized, guardrailed prompts for the AI Chat Analyst."""

from typing import Any, Dict
from app.ai_chat.builders.chat_context_builder import ChatContextBuilder

CHAT_SYSTEM_PROMPT = """You are the DecisionOS AI Business Analyst.
You answer business questions using ONLY the supplied DecisionOS intelligence context.

STRICT GUARDRAILS & INSTRUCTIONS:
1. The deterministic DecisionOS intelligence is authoritative. Ground all claims directly in the supplied context.
2. NEVER invent or hallucinate metrics, findings, root causes, recommendations, or business facts.
3. DO NOT calculate new business metrics or infer unsupported causal relationships.
4. When discussing recommendations, reference ONLY recommendations already generated by DecisionOS.
5. If the requested information does not exist in the supplied context, explicitly state that DecisionOS does not currently have enough evidence to answer the question.
6. Clearly distinguish evidence from strategic interpretation.
7. Maintain conversational continuity by referencing prior discussion in the conversation history when relevant.
8. Use concise, executive-grade business language.
9. ALWAYS respond ONLY in valid, well-formed JSON matching the specified schema format precisely.
"""


class ChatPromptBuilder:
    """
    Constructs standardized, low-hallucination prompts for conversational Q&A.
    """

    @classmethod
    def get_system_prompt(cls) -> str:
        return CHAT_SYSTEM_PROMPT

    @classmethod
    def build_chat_prompt(cls, user_question: str, context: Dict[str, Any]) -> str:
        context_json = ChatContextBuilder.to_json_str(context)

        return f"""Task: Answer the user's business question using ONLY the structured corporate context below.

Structured Corporate Context:
```json
{context_json}
```

User Question:
"{user_question}"

Required JSON Output Schema:
{{
  "answer": "<Executive-grade business answer grounded strictly in the context>",
  "confidence": <Float confidence score between 0.0 and 1.0>,
  "sources": [
    "<Explicit reference to cited findings, root causes, or recommendations, e.g. 'finding:<title>', 'rca:<title>', 'rec:<title>'>"
  ]
}}

Respond ONLY in valid JSON matching this schema."""
