"""Constants package for Phase 11.0, 11.1, and 11.2 Portfolio Intelligence."""

from app.portfolio.constants.portfolio_constants import (
    DEFAULT_LOOKBACK_DAYS,
    DEGRADED_HEALTH_SCORE,
    HEALTHY_HEALTH_SCORE,
    MIN_BENCHMARK_WORKSPACES,
    PORTFOLIO_VERSION,
    VALID_LOOKBACK_DAYS,
    BenchmarkTier,
    PortfolioStatus,
)
from app.portfolio.constants.benchmark_constants import (
    BENCHMARK_TIER_THRESHOLDS,
    BENCHMARK_VERSION,
    PEER_GROUP_THRESHOLDS,
    PORTFOLIO_HEALTH_THRESHOLDS,
    ExecutiveBenchmarkTier,
    PeerGroup,
    PortfolioHealthCategory,
)
from app.portfolio.trends.constants import (
    BENCHMARK_SCHEMA_VERSION,
    DEFAULT_TREND_WINDOW,
    MIN_TREND_DATA_POINTS,
    MovementCategory,
    PEER_GROUP_LEVELS,
    PEER_GROUP_RANGES,
    PERCENT_CHANGE_MINOR,
    PERCENT_CHANGE_MODERATE,
    TREND_DIRECTION_THRESHOLD,
    TREND_STRENGTH_MINOR,
    TREND_STRENGTH_MODERATE,
    TrendDirection,
    TrendStrength,
    VALID_TREND_WINDOWS,
)

__all__ = [
    "PORTFOLIO_VERSION",
    "MIN_BENCHMARK_WORKSPACES",
    "VALID_LOOKBACK_DAYS",
    "DEFAULT_LOOKBACK_DAYS",
    "HEALTHY_HEALTH_SCORE",
    "DEGRADED_HEALTH_SCORE",
    "PortfolioStatus",
    "BenchmarkTier",
    "TrendDirection",
    "BENCHMARK_VERSION",
    "ExecutiveBenchmarkTier",
    "PeerGroup",
    "PortfolioHealthCategory",
    "BENCHMARK_TIER_THRESHOLDS",
    "PEER_GROUP_THRESHOLDS",
    "PORTFOLIO_HEALTH_THRESHOLDS",
    "BENCHMARK_SCHEMA_VERSION",
    "VALID_TREND_WINDOWS",
    "DEFAULT_TREND_WINDOW",
    "MIN_TREND_DATA_POINTS",
    "TREND_DIRECTION_THRESHOLD",
    "TREND_STRENGTH_MINOR",
    "TREND_STRENGTH_MODERATE",
    "PERCENT_CHANGE_MINOR",
    "PERCENT_CHANGE_MODERATE",
    "TrendStrength",
    "MovementCategory",
    "PEER_GROUP_RANGES",
    "PEER_GROUP_LEVELS",
]
