import React from 'react';
import { X, ArrowDown, ShieldCheck, Database, Target, AlertTriangle, CheckCircle2, GitBranch, Cpu } from 'lucide-react';

export interface LineageStep {
  step: number;
  type: string;
  name: string;
  metric?: string;
  confidence: number;
}

export interface ExplainabilityDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  metricValue?: string;
  lineageSteps?: LineageStep[];
  aiExplanation?: string;
}

export const ExplainabilityDrawer: React.FC<ExplainabilityDrawerProps> = ({
  isOpen,
  onClose,
  title,
  metricValue,
  lineageSteps = [
    { step: 1, type: 'DATASET', name: 'Master Orders Telemetry Stream', metric: '1,420,000 live rows', confidence: 0.98 },
    { step: 2, type: 'KPI', name: 'Delivery Latency in Southeastern Region', metric: '5.4 days (+68.8% delay)', confidence: 0.95 },
    { step: 3, type: 'ROOT_CAUSE', name: 'Secondary Hub Dispatch Bottleneck', metric: 'Carrier compliance 78.4%', confidence: 0.94 },
    { step: 4, type: 'RECOMMENDATION', name: 'Carrier Rebalancing & SLA Penalties', metric: '92.8% historical success rate', confidence: 0.92 },
    { step: 5, type: 'INITIATIVE', name: 'INIT-2026-001: Win-Back & Logistics Fix', metric: 'In-progress execution (78%)', confidence: 0.95 },
    { step: 6, type: 'OUTCOME', name: 'Realized ARR Recovery', metric: '+$124,000 verified ARR lift', confidence: 0.96 },
  ],
  aiExplanation = "This metric was mathematically generated by RootCauseEngine and verified by Digital Twin simulation runs. Lineage traces back to regional carrier SLA non-compliance in Southeastern hubs.",
}) => {
  if (!isOpen) return null;

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.75)',
        backdropFilter: 'blur(6px)',
        zIndex: 200,
        display: 'flex',
        justifyContent: 'flex-end',
        animation: 'fadeIn 0.2s ease',
      }}
      onClick={onClose}
    >
      <div
        style={{
          width: '540px',
          maxWidth: '90vw',
          height: '100%',
          backgroundColor: '#090D14',
          borderLeft: '1px solid #1E293B',
          padding: '28px',
          overflowY: 'auto',
          display: 'flex',
          flexDirection: 'column',
          gap: '20px',
          boxShadow: '-20px 0 50px rgba(0,0,0,0.9)',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #1E293B', paddingBottom: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <ShieldCheck size={16} color="#10B981" />
              <span style={{ fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.08em', color: '#10B981', fontWeight: 700 }}>
                Deterministic Causal Provenance
              </span>
            </div>
            <h2 style={{ fontSize: '1.25rem', fontWeight: 800, color: '#FFFFFF', margin: 0 }}>{title}</h2>
          </div>
          <button
            onClick={onClose}
            style={{
              background: 'rgba(30, 41, 59, 0.5)',
              border: '1px solid #334155',
              color: '#94A3B8',
              borderRadius: '6px',
              padding: '6px',
              cursor: 'pointer',
            }}
          >
            <X size={16} />
          </button>
        </div>

        {/* Metric Banner */}
        {metricValue && (
          <div style={{ background: 'linear-gradient(135deg, rgba(56, 189, 248, 0.1), rgba(15, 23, 42, 0.8))', border: '1px solid rgba(56, 189, 248, 0.25)', borderRadius: '8px', padding: '14px 18px' }}>
            <div style={{ fontSize: '0.75rem', color: '#94A3B8', textTransform: 'uppercase', fontWeight: 600 }}>Active Value & Delta</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#38BDF8', marginTop: '2px' }}>{metricValue}</div>
          </div>
        )}

        {/* AI Explanation Callout */}
        <div style={{ background: 'rgba(15, 23, 42, 0.9)', border: '1px solid #1E293B', borderRadius: '8px', padding: '16px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '6px', color: '#38BDF8', fontSize: '0.8rem', fontWeight: 700, marginBottom: '6px' }}>
            <Cpu size={14} />
            <span>AI Grounded Explanation</span>
          </div>
          <p style={{ fontSize: '0.85rem', color: '#CBD5E1', lineHeight: 1.5, margin: 0 }}>
            {aiExplanation}
          </p>
        </div>

        {/* Provenance Steps DAG */}
        <div>
          <div style={{ fontSize: '0.78rem', textTransform: 'uppercase', letterSpacing: '0.06em', color: '#64748B', fontWeight: 700, marginBottom: '12px' }}>
            Multi-Hop Provenance Chain (6 Hops)
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {lineageSteps.map((step, idx) => (
              <React.Fragment key={step.step}>
                <div
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '12px 14px',
                    background: 'rgba(15, 23, 42, 0.7)',
                    border: '1px solid #1E293B',
                    borderRadius: '8px',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                    <div
                      style={{
                        width: '26px',
                        height: '26px',
                        borderRadius: '50%',
                        background: 'rgba(56, 189, 248, 0.15)',
                        color: '#38BDF8',
                        fontSize: '0.75rem',
                        fontWeight: 800,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                      }}
                    >
                      {step.step}
                    </div>
                    <div>
                      <div style={{ fontSize: '0.68rem', textTransform: 'uppercase', color: '#64748B', fontWeight: 700 }}>
                        {step.type}
                      </div>
                      <div style={{ fontSize: '0.85rem', color: '#F1F5F9', fontWeight: 600 }}>
                        {step.name}
                      </div>
                      {step.metric && (
                        <div style={{ fontSize: '0.75rem', color: '#38BDF8', marginTop: '2px' }}>
                          {step.metric}
                        </div>
                      )}
                    </div>
                  </div>
                  <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '0.68rem', color: '#64748B' }}>Confidence</div>
                    <div style={{ fontSize: '0.8rem', fontWeight: 700, color: '#10B981' }}>
                      {Math.round(step.confidence * 100)}%
                    </div>
                  </div>
                </div>

                {idx < lineageSteps.length - 1 && (
                  <div style={{ display: 'flex', justifyContent: 'center', margin: '-4px 0' }}>
                    <ArrowDown size={14} color="#475569" />
                  </div>
                )}
              </React.Fragment>
            ))}
          </div>
        </div>

        {/* Footer Actions */}
        <div style={{ marginTop: 'auto', borderTop: '1px solid #1E293B', paddingTop: '16px', display: 'flex', gap: '10px' }}>
          <button
            onClick={onClose}
            style={{
              flex: 1,
              padding: '10px',
              backgroundColor: '#1E293B',
              border: 'none',
              borderRadius: '6px',
              color: '#FFFFFF',
              fontSize: '0.82rem',
              fontWeight: 700,
              cursor: 'pointer',
            }}
          >
            Close Provenance
          </button>
        </div>
      </div>
    </div>
  );
};
