/**
 * Role-to-Permission Matrix Configuration
 */
export type UserRole = 'ADMIN' | 'EXECUTIVE' | 'ANALYST' | 'VIEWER';

export const PERMISSIONS = {
  VIEW_PORTFOLIO: 'VIEW_PORTFOLIO',
  ALLOCATE_CAPITAL: 'ALLOCATE_CAPITAL',
  VIEW_REPORTS: 'VIEW_REPORTS',
  RUN_SCENARIOS: 'RUN_SCENARIOS',
  APPROVE_DECISIONS: 'APPROVE_DECISIONS',
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ORGANIZATION: 'MANAGE_ORGANIZATION',
  EXECUTE_PLAYBOOKS: 'EXECUTE_PLAYBOOKS',
  VIEW_BENCHMARKS: 'VIEW_BENCHMARKS',
  DISPATCH_AGENTS: 'DISPATCH_AGENTS',
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<UserRole, PermissionKey[]> = {
  ADMIN: [
    'VIEW_PORTFOLIO',
    'ALLOCATE_CAPITAL',
    'VIEW_REPORTS',
    'RUN_SCENARIOS',
    'APPROVE_DECISIONS',
    'MANAGE_USERS',
    'MANAGE_ORGANIZATION',
    'EXECUTE_PLAYBOOKS',
    'VIEW_BENCHMARKS',
    'DISPATCH_AGENTS',
  ],
  EXECUTIVE: [
    'VIEW_PORTFOLIO',
    'ALLOCATE_CAPITAL',
    'VIEW_REPORTS',
    'RUN_SCENARIOS',
    'APPROVE_DECISIONS',
    'EXECUTE_PLAYBOOKS',
    'VIEW_BENCHMARKS',
    'DISPATCH_AGENTS',
  ],
  ANALYST: [
    'VIEW_PORTFOLIO',
    'VIEW_REPORTS',
    'RUN_SCENARIOS',
    'VIEW_BENCHMARKS',
  ],
  VIEWER: [
    'VIEW_PORTFOLIO',
    'VIEW_REPORTS',
  ],
};
