import React from 'react';
import {
  LayoutDashboard,
  Globe,
  DollarSign,
  BookOpen,
  ShieldAlert,
  Bot,
  PieChart,
  Database,
  AlertTriangle,
  Lightbulb,
  MessageSquare,
  GitMerge,
  FileText,
  PlayCircle,
  Target,
  Activity,
  Scale,
  TrendingUp,
  Play,
  HeartPulse,
  Settings,
  Clock,
  Send,
  Key,
  ShieldCheck,
  Server,
  Layers,
} from 'lucide-react';

export interface RouteMetadata {
  path: string;
  title: string;
  category: 'EXECUTIVE_COMMAND' | 'MULTI_PORTFOLIO' | 'INTELLIGENCE' | 'STRATEGY' | 'ENTERPRISE_OS' | 'ADMINISTRATION';
  icon: any;
  badge?: string;
  badgeColor?: string;
  permission?: string;
  featureFlag?: string;
  shortcut?: string;
  description: string;
}

export const routesConfig: RouteMetadata[] = [
  // 1. Executive Command
  {
    path: '/enterprise',
    title: 'Enterprise Command',
    category: 'EXECUTIVE_COMMAND',
    icon: LayoutDashboard,
    badge: 'OS v1',
    badgeColor: '#38BDF8',
    description: 'Flagship executive decision mission control and intelligence rollup',
  },
  {
    path: '/boardroom',
    title: 'Executive Boardroom',
    category: 'EXECUTIVE_COMMAND',
    icon: FileText,
    badge: 'BOARD',
    badgeColor: '#F59E0B',
    shortcut: 'G+B',
    permission: 'VIEW_REPORTS',
    description: 'Board presentation decks, executive briefings, and CEO sign-offs',
  },
  {
    path: '/portfolio-rollup',
    title: 'Multi-Portfolio Rollup',
    category: 'MULTI_PORTFOLIO',
    icon: Globe,
    badge: 'ENTERPRISE',
    badgeColor: '#10B981',
    shortcut: 'G+P',
    permission: 'VIEW_PORTFOLIO',
    description: 'Global hierarchy browser (Region → Division → Business Unit)',
  },
  {
    path: '/capital-allocation',
    title: 'Capital Allocation Studio',
    category: 'MULTI_PORTFOLIO',
    icon: DollarSign,
    badge: '$1M ROI',
    badgeColor: '#A855F7',
    shortcut: 'G+C',
    permission: 'ALLOCATE_CAPITAL',
    description: 'Mathematical capital deployment optimization and ROI curve comparison',
  },
  {
    path: '/kpi-dictionary',
    title: 'KPI Dictionary',
    category: 'MULTI_PORTFOLIO',
    icon: BookOpen,
    badge: 'DICT',
    badgeColor: '#F59E0B',
    shortcut: 'G+K',
    description: 'Centralized enterprise metric formulas, owners, and lineage metadata',
  },
  {
    path: '/risk-concentration',
    title: 'Risk Concentration',
    category: 'MULTI_PORTFOLIO',
    icon: ShieldAlert,
    badge: 'RADAR',
    badgeColor: '#EF4444',
    description: 'Customer ARR and geographic revenue concentration risk detector',
  },
  {
    path: '/integrations',
    title: 'Enterprise Integrations',
    category: 'ADMINISTRATION',
    icon: Layers,
    badge: 'SYNC',
    badgeColor: '#10B981',
    description: 'Salesforce, SAP, Oracle, Jira, ServiceNow, Slack, Teams Connectors',
  },
  {
    path: '/enterprise-data',
    title: 'Data Reliability Center',
    category: 'ADMINISTRATION',
    icon: Database,
    badge: '99.4%',
    badgeColor: '#10B981',
    description: 'Data quality assessments, connector freshness, and schema fidelity',
  },
  {
    path: '/ai-governance',
    title: 'AI Usage Governance',
    category: 'INTELLIGENCE',
    icon: Bot,
    badge: 'AUDIT',
    badgeColor: '#A855F7',
    description: 'AI prompt audits, token cost tracking, and evidence citation verification',
  },
  {
    path: '/intelligence-delivery',
    title: 'Intelligence Delivery',
    category: 'STRATEGY',
    icon: Send,
    badge: 'AUTO',
    badgeColor: '#38BDF8',
    description: 'Scheduled multi-channel intelligence distribution (Slack, Email, Teams)',
  },
  {
    path: '/api-platform',
    title: 'Enterprise API Platform',
    category: 'ADMINISTRATION',
    icon: Key,
    badge: 'API',
    badgeColor: '#F59E0B',
    description: 'Public REST Gateway, API keys, usage quotas, and developer documentation',
  },
  {
    path: '/administration',
    title: 'Enterprise Administration',
    category: 'ADMINISTRATION',
    icon: Settings,
    badge: 'ADMIN',
    badgeColor: '#38BDF8',
    permission: 'MANAGE_ORGANIZATION',
    description: 'Unified administration console, white-label branding, and retention rules',
  },
  {
    path: '/security-center',
    title: 'Security & Compliance',
    category: 'ADMINISTRATION',
    icon: ShieldCheck,
    badge: 'SOC2',
    badgeColor: '#10B981',
    description: 'SOC2 Type II, ISO 27001, GDPR compliance posture, and immutable audit logs',
  },
  {
    path: '/platform-ops',
    title: 'Platform Operations',
    category: 'ADMINISTRATION',
    icon: Server,
    badge: '99.98%',
    badgeColor: '#10B981',
    description: 'System uptime SLA, worker threads, gateway latency, and releases',
  },
  {
    path: '/agents',
    title: 'Autonomous Agents',
    category: 'INTELLIGENCE',
    icon: Bot,
    badge: 'AGENTS',
    badgeColor: '#A855F7',
    shortcut: 'G+A',
    permission: 'DISPATCH_AGENTS',
    description: '6 Specialized Enterprise Agents & Multi-Agent Collaboration DAG',
  },
  {
    path: '/portfolio',
    title: 'Portfolio Intelligence',
    category: 'INTELLIGENCE',
    icon: PieChart,
    badge: 'PORTFOLIO',
    badgeColor: '#38BDF8',
    permission: 'VIEW_PORTFOLIO',
    description: 'Portfolio scorecards and health explainability decomposition',
  },
  {
    path: '/data-management',
    title: 'Data Management',
    category: 'ADMINISTRATION',
    icon: Database,
    badge: 'DATA',
    badgeColor: '#10B981',
    description: 'Dataset ingestion, schema mappings, validation reports, and lineage',
  },
  {
    path: '/diagnostics',
    title: 'Diagnostic Intelligence',
    category: 'INTELLIGENCE',
    icon: AlertTriangle,
    shortcut: 'G+D',
    description: 'Deterministic findings and root cause causal explainability',
  },
  {
    path: '/recommendations',
    title: 'Recommendations',
    category: 'INTELLIGENCE',
    icon: Lightbulb,
    description: 'Ranked strategic recommendations and trade-off ROI matrix',
  },
  {
    path: '/decision-copilot',
    title: 'AI Decision Copilot',
    category: 'INTELLIGENCE',
    icon: MessageSquare,
    badge: 'COPILOT',
    badgeColor: '#38BDF8',
    description: 'Explainable AI analyst workspace with institutional memory recall',
  },
  {
    path: '/knowledge-graph',
    title: 'Knowledge Graph',
    category: 'INTELLIGENCE',
    icon: GitMerge,
    badge: 'DAG',
    badgeColor: '#A855F7',
    description: 'Interactive causal enterprise decision DAG explorer',
  },
  {
    path: '/reports',
    title: 'Executive Reports',
    category: 'STRATEGY',
    icon: FileText,
    badge: 'REPORTS',
    badgeColor: '#F59E0B',
    shortcut: 'G+R',
    permission: 'VIEW_REPORTS',
    description: 'Executive report generation and interactive PDF builder',
  },
  {
    path: '/digital-twin',
    title: 'Digital Twin & Scenarios',
    category: 'STRATEGY',
    icon: PlayCircle,
    badge: 'TWIN',
    badgeColor: '#A855F7',
    permission: 'RUN_SCENARIOS',
    description: 'Enterprise digital twin dynamic simulation gauges & stress testing',
  },
  {
    path: '/strategy-execution',
    title: 'Strategy Execution',
    category: 'STRATEGY',
    icon: Target,
    badge: 'VALUE',
    badgeColor: '#10B981',
    shortcut: 'G+S',
    description: 'Strategic initiatives, milestone tracking, and benefits realization',
  },
  {
    path: '/monitoring',
    title: 'Continuous Monitoring',
    category: 'ENTERPRISE_OS',
    icon: Activity,
    badge: 'LIVE',
    badgeColor: '#EF4444',
    shortcut: 'G+M',
    description: 'Real-time predictive alerting, SLA triage, and postmortems',
  },
  {
    path: '/governance',
    title: 'Decision Governance',
    category: 'ENTERPRISE_OS',
    icon: Scale,
    badge: 'GOV',
    badgeColor: '#10B981',
    permission: 'APPROVE_DECISIONS',
    description: 'Permanent Decision Registry, policy rules enforcer, and pre-simulations',
  },
  {
    path: '/competitive-intelligence',
    title: 'Competitive Benchmarks',
    category: 'ENTERPRISE_OS',
    icon: TrendingUp,
    badge: 'BENCH',
    badgeColor: '#F59E0B',
    permission: 'VIEW_BENCHMARKS',
    description: 'Industry median/top quartile comparisons and scenario feeder',
  },
  {
    path: '/operating-system',
    title: 'Autonomous Playbooks',
    category: 'ENTERPRISE_OS',
    icon: Play,
    badge: 'PLAY',
    badgeColor: '#A855F7',
    permission: 'EXECUTE_PLAYBOOKS',
    description: 'Reusable playbook templates, execution streams, and rollback controls',
  },
  {
    path: '/os-health',
    title: 'Enterprise OS Health',
    category: 'ENTERPRISE_OS',
    icon: HeartPulse,
    badge: '94.8',
    badgeColor: '#10B981',
    description: 'Platform operating score and system reliability metrics',
  },
  {
    path: '/jobs',
    title: 'Background Jobs',
    category: 'ADMINISTRATION',
    icon: Clock,
    badge: 'JOBS',
    badgeColor: '#38BDF8',
    description: 'Task processing queue, scenario runs, and report generation',
  },
  {
    path: '/admin',
    title: 'System Administration',
    category: 'ADMINISTRATION',
    icon: Settings,
    badge: 'ADMIN',
    badgeColor: '#64748B',
    permission: 'MANAGE_ORGANIZATION',
    description: 'Multi-tenant SaaS settings, user RBAC, API keys, and audit center',
  },
];
